# Generated by Django 5.1 on 2024-09-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelDestinations_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
