# Generated by Django 5.1 on 2024-09-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_destinations_app', '0002_remove_destination_description_destination_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
