# Generated by Django 5.1 on 2024-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awesome_destinations_app', '0005_alter_destination_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
    ]
