services:
  - type: web
    name: your-service-name
    env: python  # Use Python environment
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py runserver 0.0.0.0:8000"
